version: "3.8"
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: demo
    container_name: demo
    networks:
      - net
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - net

networks:
  net:
    name: net
    driver: bridge